# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 https://ishanshrimali.github.io/
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:              'Ishan Shrimali'
  name:              'Ishan Shrimali'
  url:               ''
  email:             ''

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
